# ##Sebelum di-edit
# version: "3.10"
# services:
#   web:
#     build: .
#     ports:
#       - "8000:5000"
#     volumes:
#       - .:/code
#     environment:
#       FLASK_DEBUG: True 
#   redis:
#     image: "redis:alpine"

## Sesudah di-edit
version: "3.10"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"
